//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casewise.GraphAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Casewise.GraphAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now restart..
        /// </summary>
        public static string APPLICATION_WILL_RESTART {
            get {
                return ResourceManager.GetString("APPLICATION_WILL_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Casewise_Icon {
            get {
                object obj = ResourceManager.GetObject("Casewise_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string CTX_DESELECT_ALL {
            get {
                return ResourceManager.GetString("CTX_DESELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string CTX_SELECT_ALL {
            get {
                return ResourceManager.GetString("CTX_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while generating diagram.
        /// </summary>
        public static string CWDESIGNER_ERROR_WHILE_GENERATING {
            get {
                return ResourceManager.GetString("CWDESIGNER_ERROR_WHILE_GENERATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diagrams have been correctly generated.
        /// </summary>
        public static string CWDESIGNER_MANY_DIAGRAM_GENERATED {
            get {
                return ResourceManager.GetString("CWDESIGNER_MANY_DIAGRAM_GENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your diagram has been correctly generated.
        /// </summary>
        public static string CWDESIGNER_ONE_DIAGRAM_GENERATED_DONE {
            get {
                return ResourceManager.GetString("CWDESIGNER_ONE_DIAGRAM_GENERATED_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the diagram.
        /// </summary>
        public static string CWDESIGNER_OPEN_DIAGRAM {
            get {
                return ResourceManager.GetString("CWDESIGNER_OPEN_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file for {0} was not found, please create one next to the exe.
        /// </summary>
        public static string ERROR_CONFIGURATION_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_CONFIGURATION_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Object Type {0} doesn&apos;t exists in the template {1} Palette..
        /// </summary>
        public static string ERROR_OBJETTYPE_IS_NOT_IN_PALETTEENTRY {
            get {
                return ResourceManager.GetString("ERROR_OBJETTYPE_IS_NOT_IN_PALETTEENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Object Type ID {0} is missing.
        /// </summary>
        public static string ERROR_WARN_MISSING_cwLightObjectType {
            get {
                return ResourceManager.GetString("ERROR_WARN_MISSING_cwLightObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while enabling the model {0}:{1} please check the error file located {2} for more information..
        /// </summary>
        public static string ERROR_XMLIMPORTEXPORT {
            get {
                return ResourceManager.GetString("ERROR_XMLIMPORTEXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FORM_ADDITEM_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("FORM_ADDITEM_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FORM_ADDITEM_BUTTON_CREATE {
            get {
                return ResourceManager.GetString("FORM_ADDITEM_BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item already exists, please choose a new name.
        /// </summary>
        public static string FORM_ADDITEM_ITEM_ALEADY_EXISTS {
            get {
                return ResourceManager.GetString("FORM_ADDITEM_ITEM_ALEADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New auto diagram template.
        /// </summary>
        public static string FORM_ADDITEM_LABEL_SET_ITEM_NAME {
            get {
                return ResourceManager.GetString("FORM_ADDITEM_LABEL_SET_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on node {1} which is a {2}.
        /// </summary>
        public static string GUI_APPEND_ERROR {
            get {
                return ResourceManager.GetString("GUI_APPEND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts.
        /// </summary>
        public static string GUI_EDITMODE_GROUPBOXDESIGN_TEXT {
            get {
                return ResourceManager.GetString("GUI_EDITMODE_GROUPBOXDESIGN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string GUI_EDITMODE_GROUPBOXOPTIONS_TEXT {
            get {
                return ResourceManager.GetString("GUI_EDITMODE_GROUPBOXOPTIONS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_loading {
            get {
                object obj = ResourceManager.GetObject("image_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_logo_graphapi {
            get {
                object obj = ResourceManager.GetObject("image_logo_graphapi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_model_hover {
            get {
                object obj = ResourceManager.GetObject("image_model_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_model_small {
            get {
                object obj = ResourceManager.GetObject("image_model_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_option_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("image_option_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_option_close_32x32 {
            get {
                object obj = ResourceManager.GetObject("image_option_close_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_option_help_32x32 {
            get {
                object obj = ResourceManager.GetObject("image_option_help_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_option_prev_32x32 {
            get {
                object obj = ResourceManager.GetObject("image_option_prev_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_delete {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_generate {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_generate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_layout {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_minus {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_node {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_node", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_plus {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_reload {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_tvicon_save {
            get {
                object obj = ResourceManager.GetObject("image_tvicon_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Models.
        /// </summary>
        public static string LAUNCHER_OPTIONS_BUTTONS_BACK_TOOLTIP {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_BUTTONS_BACK_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LAUNCHER_OPTIONS_BUTTONS_CLOSE_TOOLTIP {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_BUTTONS_CLOSE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string LAUNCHER_OPTIONS_BUTTONS_HELP_TOOLTIP {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_BUTTONS_HELP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string LAUNCHER_OPTIONS_BUTTONS_OPTIONS_CONTEXT_MENU_ADD_ITEM {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_BUTTONS_OPTIONS_CONTEXT_MENU_ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Model.
        /// </summary>
        public static string LAUNCHER_OPTIONS_BUTTONS_OPTIONS_CONTEXT_MENU_ENABLE_MODEL {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_BUTTONS_OPTIONS_CONTEXT_MENU_ENABLE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LAUNCHER_OPTIONS_BUTTONS_OPTIONS_TOOLTIP {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_BUTTONS_OPTIONS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an item.
        /// </summary>
        public static string LAUNCHER_OPTIONS_TOOLTIP_ADD_ITEM {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_TOOLTIP_ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable a model.
        /// </summary>
        public static string LAUNCHER_OPTIONS_TOOLTIP_ENABLE_MODEL {
            get {
                return ResourceManager.GetString("LAUNCHER_OPTIONS_TOOLTIP_ENABLE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casewise Labs - No support is provided by Casewise HelpDesk.
        /// </summary>
        public static string LAUNCHER_WARNING_TEXT {
            get {
                return ResourceManager.GetString("LAUNCHER_WARNING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UUID of the object inside the repository.
        /// </summary>
        public static string PSF_CONFIGURATION_NODE_NODEUUID_HELP {
            get {
                return ResourceManager.GetString("PSF_CONFIGURATION_NODE_NODEUUID_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node UUID.
        /// </summary>
        public static string PSF_CONFIGURATION_NODE_NODEUUID_NAME {
            get {
                return ResourceManager.GetString("PSF_CONFIGURATION_NODE_NODEUUID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take care of errors before saving the node..
        /// </summary>
        public static string PSF_CONFIGURATION_NODE_SAVE_KO_BECAUSE_RULES_NOT_RESPECTED {
            get {
                return ResourceManager.GetString("PSF_CONFIGURATION_NODE_SAVE_KO_BECAUSE_RULES_NOT_RESPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node has been saved..
        /// </summary>
        public static string PSF_CONFIGURATION_NODE_SAVE_OK {
            get {
                return ResourceManager.GetString("PSF_CONFIGURATION_NODE_SAVE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You connection to the repositroy was closed please re-perform your operation.
        /// </summary>
        public static string PSF_DBLINK_ERROR {
            get {
                return ResourceManager.GetString("PSF_DBLINK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string PSF_FILTER_HEADER_OPERATION {
            get {
                return ResourceManager.GetString("PSF_FILTER_HEADER_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string PSF_FILTER_HEADER_PROPERTY {
            get {
                return ResourceManager.GetString("PSF_FILTER_HEADER_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PSF_FILTER_HEADER_VALUE {
            get {
                return ResourceManager.GetString("PSF_FILTER_HEADER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string PSF_PROPERTY_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("PSF_PROPERTY_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can&apos;t be empty.
        /// </summary>
        public static string PSF_PROPERTY_VALUE_CANT_BE_EMPTY {
            get {
                return ResourceManager.GetString("PSF_PROPERTY_VALUE_CANT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Object Type.
        /// </summary>
        public static string PSF_TN_ADD_OBJECT_TYPE {
            get {
                return ResourceManager.GetString("PSF_TN_ADD_OBJECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string PSF_TN_CTX_COLLAPSE {
            get {
                return ResourceManager.GetString("PSF_TN_CTX_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PSF_TN_CTX_DELETE {
            get {
                return ResourceManager.GetString("PSF_TN_CTX_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string PSF_TN_CTX_EXPAND_ALL {
            get {
                return ResourceManager.GetString("PSF_TN_CTX_EXPAND_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PSF_TN_CTX_SAVE {
            get {
                return ResourceManager.GetString("PSF_TN_CTX_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the {0} property with a valid value.
        /// </summary>
        public static string PSF_TN_FORMAT_ERROR_ON_PROPERTY {
            get {
                return ResourceManager.GetString("PSF_TN_FORMAT_ERROR_ON_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the required name is under than 255 characters.
        /// </summary>
        public static string PSF_TN_LABEL_SHOULD_HAVE_LESSTHAN_255_CHAR {
            get {
                return ResourceManager.GetString("PSF_TN_LABEL_SHOULD_HAVE_LESSTHAN_255_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the association type is used, the selection will be done on the target objects of the provided association type.
        /// </summary>
        public static string PSF_TN_NODE_ASSOCIATION_TYPE_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_ASSOCIATION_TYPE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Type To Target.
        /// </summary>
        public static string PSF_TN_NODE_ASSOCIATION_TYPE_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_ASSOCIATION_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Association Type.
        /// </summary>
        public static string PSF_TN_NODE_CTX_ADD_ASSOCIATION_TYPE {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_CTX_ADD_ASSOCIATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the node in order to find and remeber it easily.
        /// </summary>
        public static string PSF_TN_NODE_NAME_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_NAME_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name.
        /// </summary>
        public static string PSF_TN_NODE_NAME_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_NAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object type you want to run the operation on.
        /// </summary>
        public static string PSF_TN_NODE_OBJECT_TYPE_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OBJECT_TYPE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type.
        /// </summary>
        public static string PSF_TN_NODE_OBJECT_TYPE_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OBJECT_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To filter the object type using properties, AND condition.
        /// </summary>
        public static string PSF_TN_NODE_OG_FILTER_AND_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_FILTER_AND_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Properties (AND).
        /// </summary>
        public static string PSF_TN_NODE_OG_FILTER_AND_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_FILTER_AND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object group ID is used by the Web Designer in order to select the Object Group.
        /// </summary>
        public static string PSF_TN_NODE_OG_OGID_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_OGID_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Group ID.
        /// </summary>
        public static string PSF_TN_NODE_OG_OGID_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_OGID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the properties to export (NAME should always be selected : default behaviour).
        /// </summary>
        public static string PSF_TN_NODE_OG_SELECTEDPROPERTIES_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_SELECTEDPROPERTIES_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Properties.
        /// </summary>
        public static string PSF_TN_NODE_OG_SELECTEDPROPERTIES_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_SELECTEDPROPERTIES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property which will be used to sort the objects.
        /// </summary>
        public static string PSF_TN_NODE_OG_SORTON_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_SORTON_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort On.
        /// </summary>
        public static string PSF_TN_NODE_OG_SORTON_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_SORTON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if the sort by should be reversed.
        /// </summary>
        public static string PSF_TN_NODE_OG_SORTON_REVERSE_HELP {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_SORTON_REVERSE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Reverse.
        /// </summary>
        public static string PSF_TN_NODE_OG_SORTON_REVERSE_NAME {
            get {
                return ResourceManager.GetString("PSF_TN_NODE_OG_SORTON_REVERSE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation Required.
        /// </summary>
        public static string PSF_TN_POPUP_DELETE_NODE_TEXT {
            get {
                return ResourceManager.GetString("PSF_TN_POPUP_DELETE_NODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Node : {0}.
        /// </summary>
        public static string PSF_TN_POPUP_DELETE_NODE_TITLE {
            get {
                return ResourceManager.GetString("PSF_TN_POPUP_DELETE_NODE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string PSF_VALIDATION_RULE_TOOLTIP_TITLE_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("PSF_VALIDATION_RULE_TOOLTIP_TITLE_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to delete the root node, Please use the Casewise Administrator to delete the item.
        /// </summary>
        public static string PSF_VN_CANT_DELETE_FROM_GUI {
            get {
                return ResourceManager.GetString("PSF_VN_CANT_DELETE_FROM_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill with a float value using a dot as a separator like : 1.0 or 0.5.
        /// </summary>
        public static string PSF_VN_FLOAT_VALUE {
            get {
                return ResourceManager.GetString("PSF_VN_FLOAT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string TEXT_CATEGORY_UNDEFINED {
            get {
                return ResourceManager.GetString("TEXT_CATEGORY_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string TEXT_FALSE {
            get {
                return ResourceManager.GetString("TEXT_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Licence available for this feature..
        /// </summary>
        public static string TEXT_NO_LICENCE_AVAILABLE {
            get {
                return ResourceManager.GetString("TEXT_NO_LICENCE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been cancelled.
        /// </summary>
        public static string TEXT_OPERATION_CANCELLED {
            get {
                return ResourceManager.GetString("TEXT_OPERATION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string TEXT_OPTIONS {
            get {
                return ResourceManager.GetString("TEXT_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not saved your configuration, do you wish to save it?.
        /// </summary>
        public static string TEXT_SAVEREQUIRED_ON_CLOSE {
            get {
                return ResourceManager.GetString("TEXT_SAVEREQUIRED_ON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string TEXT_TRUE {
            get {
                return ResourceManager.GetString("TEXT_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TEXT_WARNING {
            get {
                return ResourceManager.GetString("TEXT_WARNING", resourceCulture);
            }
        }
    }
}
